version: '3.9'

services:
  entrytracker:
    build: .
    container_name: entrytracker
    depends_on:
      - db
    networks:
      - internal_net
    # אין ports

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: entrytracker
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - internal_net

networks:
  internal_net:
    driver: bridge
